#!/bin/bash
# install service in dev container

cd /workspace


# install in edit mode
pip install -e .

# install pre-commit hooks to git:
pre-commit install

cd db_migration

# Check if the database has been initialized and if not initialize it
alembic -c alembic.ini upgrade head